'use client';

import React from 'react';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { Gavel, CheckCircle2, AlertTriangle } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-white transition-colors duration-300">
      <Navbar />
      <main className="pt-32 pb-24 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 text-xs font-black uppercase tracking-[0.2em] mb-6">
              <Gavel size={14} />
              Terms of Service
            </div>
            <h1 className="text-5xl font-black mb-6 tracking-tight">User Agreement</h1>
            <p className="text-xl text-slate-500 dark:text-slate-400">
              Simple terms for a free, open tool.
            </p>
          </div>

          <div className="space-y-12 text-slate-600 dark:text-slate-400 leading-relaxed">
            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">1. License Grant</h2>
              <p>
                Tree File is provided under the <strong>MIT License</strong>. You are free to use, copy, modify, and distribute this software for both personal and commercial purposes, subject to the conditions of the license.
              </p>
            </section>

            <div className="p-8 rounded-3xl bg-amber-50 dark:bg-amber-900/10 border border-amber-200 dark:border-amber-900/50">
              <div className="flex items-center gap-3 mb-4 text-amber-600 dark:text-amber-500">
                <AlertTriangle size={24} />
                <h2 className="text-xl font-bold">2. Disclaimer of Warranty</h2>
              </div>
              <p className="text-sm leading-relaxed text-amber-900/80 dark:text-amber-100/80 font-medium">
                THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. THE AUTHORS ARE NOT LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY ARISING FROM THE USE OF THIS SOFTWARE.
              </p>
              <p className="text-xs mt-4 text-amber-800/60 dark:text-amber-200/40">
                In plain English: Use at your own risk. Always backup your important data before editing.
              </p>
            </div>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">3. AI Services</h2>
              <p>
                The AI Assistant is a feature provided "as available". We do not guarantee the accuracy, uptime, or quality of responses generated by the AI model. Do not rely on the AI for critical financial, medical, or security advice.
              </p>
            </section>

            <div className="space-y-4">
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">4. Acceptable Use</h2>
              {[
                "You agree not to use the software for illegal purposes.",
                "You acknowledge that file editing is permanent; always keep backups.",
                "We reserve the right to update these terms for future versions."
              ].map((text, i) => (
                <div key={i} className="flex items-start gap-4">
                  <CheckCircle2 size={20} className="text-teal-500 mt-1 shrink-0" />
                  <p>{text}</p>
                </div>
              ))}
            </div>

            <div className="text-center pt-12 border-t border-slate-100 dark:border-slate-900">
              <p className="text-sm font-mono text-slate-400">
                Effective Date: December 2025
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}