import React from 'react';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { Gavel, CheckCircle2 } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-white transition-colors duration-300">
      <Navbar />
      <main className="pt-32 pb-24 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 text-xs font-black uppercase tracking-[0.2em] mb-6">
              <Gavel size={14} />
              Legal Framework
            </div>
            <h1 className="text-5xl font-black mb-6 tracking-tight">Terms of Service</h1>
            <p className="text-xl text-slate-500 dark:text-slate-400">
              Developer-friendly terms for an open-source world.
            </p>
          </div>

          <div className="space-y-12 text-slate-600 dark:text-slate-400 leading-relaxed">
            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">1. Acceptance of Terms</h2>
              <p>
                By downloading or using Tree File, you agree to comply with the terms of the MIT License. This software is provided free of charge for personal and commercial use.
              </p>
            </section>

            <div className="p-8 rounded-3xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">2. Warranty Disclaimer</h2>
              <p className="italic font-mono text-sm leading-relaxed">
                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
              </p>
            </div>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">3. AI Service Usage</h2>
              <p>
                The AI features in Tree File require a valid Google Gemini API key. You are responsible for any costs incurred through the use of your own API keys. We are not responsible for the accuracy or quality of the responses generated by third-party AI models.
              </p>
            </section>

            <div className="space-y-4">
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">4. Responsible Use</h2>
              {[
                "You agree not to use the software for any illegal activities.",
                "You acknowledge that we are not liable for any data loss resulting from software errors.",
                "You are encouraged to contribute back to the project if you find bugs or missing features."
              ].map((text, i) => (
                <div key={i} className="flex items-start gap-4">
                  <CheckCircle2 size={20} className="text-emerald-500 mt-1 shrink-0" />
                  <p>{text}</p>
                </div>
              ))}
            </div>

            <div className="text-center pt-12 border-t border-slate-100 dark:border-slate-900">
              <p className="text-sm font-mono text-slate-400">
                Document Revision: v1.0.0
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}